from pathlib import Path

path = Path('frontend/src/components/SynapsePlayer.jsx')
text = path.read_text()

catalog_anchor = 'const SPEEDS = [0.5, 0.75, 1, 1.25, 1.5, 2];\n'
catalog = '''const SPEEDS = [0.5, 0.75, 1, 1.25, 1.5, 2];\nconst SOURCE_CATALOG = [\n    { provider: "castle", name: "Orbit" },\n    { provider: "vidlink", name: "Nova" },\n    { provider: "vidnest", name: "Nest" },\n    { provider: "vidzee", name: "Zen" },\n    { provider: "vidrock", name: "Rock" },\n    { provider: "vixsrc", name: "Vix" },\n];\n'''
if 'const SOURCE_CATALOG' not in text:
    text = text.replace(catalog_anchor, catalog, 1)

source_anchor = '    const captionSources = Array.from(new Map(servers.map((s) => [s.provider, s])).values()).slice(0, 6);\n'
source_block = '''    const sourceSlots = SOURCE_CATALOG.map((source) => {\n        const server = servers.find((s) => s.provider === source.provider);\n        return server\n            ? { ...server, displayName: source.name, available: true }\n            : { id: `unavailable-${source.provider}`, provider: source.provider, name: source.name, displayName: source.name, available: false };\n    });\n    const captionSources = sourceSlots.filter((s) => s.available);\n'''
text = text.replace(source_anchor, source_block, 1)

old_popout = '''                                        {servers.map((s) => (\n                                            <button\n                                                key={s.id}\n                                                onClick={() => selectServer(s)}\n                                                className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${serverId === s.id ? "bg-white text-black" : "text-white/80 hover:bg-white/10 hover:text-white"}`}\n                                            >\n                                                <span className="min-w-0 flex-1 truncate text-sm font-medium">{s.name}</span>\n                                                <img\n                                                    src="https://flagsapi.com/US/flat/24.png"\n                                                    alt="US"\n                                                    className="h-4 w-6 shrink-0 rounded-[2px] object-cover"\n                                                    loading="lazy"\n                                                />\n                                            </button>\n                                        ))}\n'''
new_popout = '''                                        {sourceSlots.map((s) => (\n                                            <button\n                                                key={s.id}\n                                                disabled={!s.available}\n                                                onClick={() => s.available && selectServer(s)}\n                                                className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${serverId === s.id ? "bg-white text-black" : s.available ? "text-white/80 hover:bg-white/10 hover:text-white" : "cursor-not-allowed text-white/28"}`}\n                                            >\n                                                <span className="min-w-0 flex-1 truncate text-sm font-medium">{s.displayName || s.name}</span>\n                                                {!s.available && <span className="text-[9px] font-medium uppercase tracking-[0.12em] text-white/28">Unavailable</span>}\n                                                <img\n                                                    src="https://flagsapi.com/US/flat/24.png"\n                                                    alt="US"\n                                                    className={`h-4 w-6 shrink-0 rounded-[2px] object-cover ${s.available ? "opacity-100" : "opacity-25"}`}\n                                                    loading="lazy"\n                                                />\n                                            </button>\n                                        ))}\n'''
if old_popout not in text:
    raise SystemExit('source popout block not found')
text = text.replace(old_popout, new_popout, 1)

old_settings = '''                                    {servers.map((s) => (\n                                        <button key={s.id} onClick={() => selectServerInSettings(s)} className={`flex w-full items-center gap-3 rounded-2xl px-5 py-4 text-left transition ${serverId === s.id ? "bg-white text-black" : "text-white/85 hover:bg-white/[0.06]"}`}>\n                                            <Cloud className="h-5 w-5 shrink-0" strokeWidth={1.6} />\n                                            <span className="min-w-0 flex-1 truncate text-[16px]">{s.name}</span>\n                                            <img src="https://flagsapi.com/US/flat/24.png" alt="US" className="h-4 w-6 rounded-[2px] object-cover" />\n                                            {serverId === s.id && <span className="text-xs opacity-55">Selected</span>}\n                                        </button>\n                                    ))}\n'''
new_settings = '''                                    {sourceSlots.map((s) => (\n                                        <button key={s.id} disabled={!s.available} onClick={() => s.available && selectServerInSettings(s)} className={`flex w-full items-center gap-3 rounded-2xl px-5 py-4 text-left transition ${serverId === s.id ? "bg-white text-black" : s.available ? "text-white/85 hover:bg-white/[0.06]" : "cursor-not-allowed text-white/25"}`}>\n                                            <Cloud className="h-5 w-5 shrink-0" strokeWidth={1.6} />\n                                            <span className="min-w-0 flex-1 truncate text-[16px]">{s.displayName || s.name}</span>\n                                            {!s.available && <span className="text-[9px] font-medium uppercase tracking-[0.12em] text-white/28">Unavailable</span>}\n                                            <img src="https://flagsapi.com/US/flat/24.png" alt="US" className={`h-4 w-6 rounded-[2px] object-cover ${s.available ? "opacity-100" : "opacity-25"}`} />\n                                            {serverId === s.id && <span className="text-xs opacity-55">Selected</span>}\n                                        </button>\n                                    ))}\n'''
if old_settings not in text:
    raise SystemExit('settings server block not found')
text = text.replace(old_settings, new_settings, 1)

path.write_text(text)
print('Zen and Rock source slots added')
