name: SynFlix

options:
  bundleIdPrefix: app.synflix
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0

targets:
  SynFlix:
    type: application
    platform: iOS
    sources:
      - path: SynFlix
    info:
      path: SynFlix/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.synflix.mobile
        PRODUCT_NAME: SynFlix
        MARKETING_VERSION: 1.9.0
        CURRENT_PROJECT_VERSION: 9
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      gatherCoverageData: false
